# Generated by Django 5.1.2 on 2024-10-21 04:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_whishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whishlist',
            new_name='Wishlist',
        ),
    ]
