# Generated by Django 5.1.2 on 2024-10-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_whishlist_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
